spring:
  kafka:
    consumer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
      auto-offset-reset: earliest
      group-id: user-group
      client-id: codaholic-client
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: evento.*
server:
  port: 3050
