spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:9092
    producer:
      client-id: codaholic-client
      properties:
        acks: 1
        spring.json.add.type.headers: false
server:
  port: 3055
